/* Automatically generated by './build/bin/build-entry.js' */

import Alter from '../../packages/alter'
import Button from '../../packages/button'
import Collapse from '../../packages/collapse'
import Copy from '../../packages/copy'
import EchartsHome from '../../packages/echarts-home'
import EchartsMatch from '../../packages/echarts-match'
import EchartsTab from '../../packages/echarts-tab'
import ElLoading from '../../packages/el-loading'
import ElMessage from '../../packages/el-message'
import Input from '../../packages/input'
import Message from '../../packages/message'
import NormalInput from '../../packages/normal-input'
import NormalInputSelect from '../../packages/normal-input-select'
import NormalTab from '../../packages/normal-tab'
import NormalTabPane from '../../packages/normal-tab-pane'
import Progress from '../../packages/progress'
import Scale from '../../packages/scale'
import Select from '../../packages/select'
import Span from '../../packages/span'
import Step from '../../packages/step'
import StepBar from '../../packages/step-bar'
import Tab from '../../packages/tab'
import TabSwiper from '../../packages/tab-swiper'
import Title from '../../packages/title'
import Tooltip from '../../packages/tooltip'
import Table from '../../packages/table'
import TableExpand from '../../packages/table-expand'
import TableMatch from '../../packages/table-match'
import TableTodo from '../../packages/table-todo'
import VerifyCode from '../../packages/verify-code'
import VerifyCodeSmall from '../../packages/verify-code-small'

import CollapseTransition from 'vue-jd-ui/src/transitions/collapse-transition'

const components = [
  Alter,
  Button,
  Collapse,
  Copy,
  EchartsHome,
  EchartsMatch,
  EchartsTab,
  Input,
  Message,
  NormalInput,
  NormalInputSelect,
  NormalTab,
  NormalTabPane,
  Progress,
  Scale,
  Select,
  Span,
  Step,
  StepBar,
  Tab,
  TabSwiper,
  Title,
  Tooltip,
  Table,
  TableExpand,
  TableMatch,
  TableTodo,
  VerifyCode,
  VerifyCodeSmall,
  CollapseTransition
]

const install = function(Vue, opts = {}) {
  Vue.component('collapse-transition', CollapseTransition)

  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.use(ElLoading.directive)

  Vue.prototype.$loading = ElLoading.service
  Vue.prototype.$message = ElMessage
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.0-dev.3',
  install,
  CollapseTransition,
  Loading: ElLoading,
  Alter,
  Button,
  Collapse,
  Copy,
  EchartsHome,
  EchartsMatch,
  EchartsTab,
  ElLoading,
  ElMessage,
  Input,
  Message,
  NormalInput,
  NormalInputSelect,
  NormalTab,
  NormalTabPane,
  Progress,
  Scale,
  Select,
  Span,
  Step,
  StepBar,
  Tab,
  TabSwiper,
  Title,
  Tooltip,
  Table,
  TableExpand,
  TableMatch,
  TableTodo,
  VerifyCode,
  VerifyCodeSmall
}
